// Generated by https://quicktype.io

import { Coupon, Messages, SimpleResponse } from '.';
import { Category } from './category.interface';
import { Product } from './product.interface';

// Generated by https://quicktype.io

export interface ProductsResponsePerPage {
    ok: boolean;
    products: Product[];
    page: number;
    numberOfPages: number;
    totalDocuments: number;
}

export interface ProductRequest {
    name: string;
    description: string;
    price: number;
    category: string;
    stock: number;
    toppings: boolean;
    extraItems: boolean;
    addon: boolean;
    image_paths?: string[];
    options?: {
        name: string;
    }[];
    typeOfPersons: number;
}

export interface ProductResponse extends SimpleResponse {
    product: Product;
}

export interface CategoriesResponsePerPage {
    ok: boolean;
    categories: Category[];
    page: number;
    numberOfPages: number;
    totalDocuments: number;
}
export interface CouponsResponse {
    ok: boolean;
    coupons: Coupon[];
    page: number;
    numberOfPages: number;
    totalDocuments: number;
}
export interface CouponResponse extends SimpleResponse {
    coupon: Coupon;
}

export interface RangeData {
    ok: boolean;
    page: number;
    numberOfPages: number;
    totalDocuments: number;
}

export interface CouponRequest {
    code: string;
    discount: string;
    with_quantity?: boolean;
    quantity?: number;
}

export interface CategoryRequest {
    name: string;
}

export interface ErrorRTKQuery {
    data: { ok: boolean; messages: Messages; status: number };
}

export interface CategoryResponse extends SimpleResponse {
    category: Category;
}
// Generated by https://quicktype.io

export interface ImagesResponse extends SimpleResponse {
    images: Image[];
    product: Product;
}

export interface Image {
    url: string;
    name: string;
    _id: string;
}

// Generated by https://quicktype.io

export interface ProductsResponse {
    ok: boolean;
    products: ProductsByCategoryResponse[];
}

export interface ProductsByCategoryResponse {
    _id: string;
    category_name: string;
    products: Product[];
}

export interface ProductByCategory extends Product {
    categoryData: Category;
}

// Generated by https://quicktype.io

export interface CategoriesResponse {
    ok: boolean;
    categories: Category[];
}
